### ISSUE TITLE
Provide Warning Messages

### ISSUE THREAD

**Issue by alafazanis** [eclipse-che4z/che-che4z-lsp-for-cobol#2091]
It would be nice if after the analyzing process is finished, you can provide along with the error messages WARNING messages as well, and in the same way as errors where lines of code that produces the error are underlined with red color, for WARNINGS we expect these lines of code that produces the WARNING to be underlined with yellow.

For example, it would we nice to have warnings for unreachable code, or moving a PIC X(n) variable to to PIC S9(n) COMP etc.

In general the core idea is to be the closest you can to the IBM Compiler

**Comment by zimlu02** [comment]
Hello,
as of now, we do support warning messages (e.g. when a token starts at the wrong area) but surely we don't cover all cases.
I have created two new issues for the examples you stated so that we can track them individually.

https://github.com/eclipse-che4z/che-che4z-lsp-for-cobol/issues/2095
https://github.com/eclipse-che4z/che-che4z-lsp-for-cobol/issues/2096

Please feel free to open other tickets for syntax to be supported.
I am closing this ticket.
Thank you
